language: php

php:
  - 7.1.3

services:
  - mysql
cache:
  directories:
    - vendor
before_script:
  - cp .env.travis .env
  - composer self-update
  - php artisan key:generate
  - php artisan migrate
script:
  - vendor/auotoload